### ISSUE TITLE
Spoofing the BundleId for when notifications are activated

### ISSUE THREAD

**Issue by mattlubner** [norio-nomura/usernotification#3]
Firstly, thanks for contributing this!

Do you know of a way to spoof the BundleId that's referenced from my CLI tool's (embedded) Info.plist for when a notification is clicked (aside from just changing the value)?

What I mean is, when I click on a notification raised by my CLI tool, I get a dialog saying: _There is no application set to open the document "com.myDomain.myTool"._ I am, however, spoofing the BundleId to be "com.myDomain.myApplication", and notifications _are_ displaying with that application's icon.

If I change the BundleId in the CLI tool's (embedded) Info.plist file to be the same as the application's BundleId, everything works as expected. However, it feels… unsafe (?) to be changing the BundleId here… it means my Xcode project has two Info.plist files with the same BundleId…!? Being new to Cocoa, are there any negative side effects from doing this I should know about?

I don't understand why the notification uses the BundleId from NSBundle for the icon, but uses the BundleId from the Info.plist for the click action…

FYI, I'm running Mavericks (10.9.1), which is set as my deployment target.

Thanks for any help!

**Comment by norio-nomura** [comment]
Hi @mattlubner,

As you can see, _usernotification_ was not created to support clicking notification.
I want to indicate only that "NSUserNotification can send without bundle" by this repository.

If you can create your app by using bundle structure, I think [terminal-notifier](https://github.com/alloy/terminal-notifier) design may be suitable.

:-)

Now, I did some test, it seems Mavericks remember the executable which sent the NSUserNotification.
As I can remember, this behavior does not change since I opened this repository.

**Comment by mattlubner** [comment]
Gotcha. Was afraid I'd have to change the CLI tool to a full-fledged app bundle. I suppose I should just keep using the spoofed value directly in the Info.plist until I run into an issue with it.

For posterity's sake, it's worth noting that spoofing the BundleId within a CLI tool's embedded Info.plist _requires_ the CLI tool to have _exactly_ the same code-signing and provisioning profiles (and possibly also entitlements) as the app bundle you are trying to spoof! This is at least true if both the CLI tool and app are within the same Xcode project.

Thanks again @norio-nomura for contributing this, it's pretty awesome that it's even possible!
